Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2022-04, with the labels that each got.

#180 New index handling method for samplesheet generator
  VERSIONLOG.md
  scripts/samplesheet_generator.py
Labels: enhancement, no validation

#181 Do not convert index 2 for finished library samples for MiSeq
  VERSIONLOG.md
  scripts/samplesheet_generator.py
Labels: enhancement, no validation

#183 Refactor 10X index pattern names
  VERSIONLOG.md
  scripts/samplesheet_generator.py
Labels: no validation

#182 Zika normalization and pooling update
  scripts/bravo_csv.py
Labels: enhancement, no validation

#184 New EPP for summarizing Aggregate QC stats into running notes
  VERSIONLOG.md
  data/QC_criteria.json
  scripts/aggregateqc_to_running_notes.py
Labels: enhancement, validation

#185 Support 10X SI-TS indexes
  VERSIONLOG.md
  data/Chromium_10X_indexes.py
  scripts/samplesheet_generator.py
Labels: enhancement, no validation
