Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2023-09, with the labels that each got.

#272 Replace mfs with ngi-nas-ns
  VERSIONLOG.md
  scripts/attach_novaseq_xml.py
  scripts/copy_run_recipe.py
  scripts/illumina_run_parameter_parser.py
  scripts/manage_demux_stats.py
  scripts/novaseq_run_recipe_generator.py
  scripts/parse_anglerfish_results.py
  scripts/quality_filter.py
  scripts/samplesheet_generator.py
  scripts/set_App_QC.py
  scripts/undemultiplexed_index.py
Labels: validation

#267 Update for move to new run notes db
  scripts/aggregateqc_to_running_notes.py
  scripts/comments_to_running_notes.py
  scripts/make_running_note_from_pooling.py
  scripts/make_running_note_from_workset.py
  scripts/write_notes_to_couchdb.py
Labels: no validation

#273 Bugfix "ONT process stared runs" DB update
  VERSIONLOG.md
  scripts/ont_send_loading_info_to_db.py
Labels: bug, no validation

#274 Fix bug with datatime in make_running_note_from_workset
  VERSIONLOG.md
  scripts/make_running_note_from_workset.py
Labels: bug, no validation

#275 Fix couchdb conflict error with running notes
  VERSIONLOG.md
  scripts/write_notes_to_couchdb.py
Labels: bug, no validation

#276 Fix parent in running notes in comments_to_running_notes
  VERSIONLOG.md
  scripts/comments_to_running_notes.py
Labels: no validation
