Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2023-10, with the labels that each got.

#278 Remove special rule for no-depletion in bravo_csv
  VERSIONLOG.md
  scripts/bravo_csv.py
Labels: enhancement, no validation

#281 Change lane yield threshold for NovaSeqXPlus 10B
  VERSIONLOG.md
  scripts/manage_demux_stats_thresholds.py
Labels: no validation

#279 Update Anglerfish samplesheet generation
  VERSIONLOG.md
  data/Chromium_10X_indexes.py
  scripts/ont_generate_samplesheet.py
Labels: enhancement, no validation

#282 Add support for Illumina DNA PCR-free protocol
  VERSIONLOG.md
  data/logbook_data.py
  scripts/comments_to_running_notes.py
Labels: validation

#283 Remove HiSeq and HiSeqX from demux EPP scripts
  VERSIONLOG.md
  scripts/manage_demux_stats.py
  scripts/manage_demux_stats_thresholds.py
Labels: bug, no validation

#285 Fix bug with multiple Tos breaking sendmail
  VERSIONLOG.md
  scripts/write_notes_to_couchdb.py
Labels: no validation
