Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2023-02, with the labels that each got.

#233 Zika refactoring for RAD-seq pooling
  VERSIONLOG.md
  scripts/bravo_csv.py
  scripts/zika.py
  scripts/zika_methods.py
Labels: enhancement, no validation

#234 Zika refactoring, hotfix
  VERSIONLOG.md
  scripts/bravo_csv.py
  scripts/zika_methods.py
  scripts/zika_utils.py
Labels: bug, enhancement, no validation

#235 Zika normalization
  scripts/bravo_csv.py
  scripts/zika_methods.py
  scripts/zika_utils.py
Labels: enhancement, no validation

#236 Enable verify index and placement epp for checking wrong well format
  VERSIONLOG.md
  scripts/index_distance_checker.py
Labels: enhancement, no validation

#238 Support nM as a valid conc unit for Aggregate QC DNA and RNA
  VERSIONLOG.md
  scripts/aggregateqc_to_running_notes.py
Labels: enhancement, no validation

#239 Troubleshoot Zika pooling
  VERSIONLOG.md
  scripts/bravo_csv.py
  scripts/zika_methods.py
Labels: bug, no validation

#240 EPPs for ONT integration
  .gitignore
  VERSIONLOG.md
  requirements.txt
  scripts/append_ont_fc_to_sample_name.py
  scripts/calculate_amounts_and_yields.py
  scripts/generate_ont_samplesheet.py
  scripts/log_udfs.py
  scripts/send_ont_loading_info_to_statusdb.py
Labels: enhancement, no validation
