Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2023-08, with the labels that each got.

#266 Small fix for running notes EPP config
  VERSIONLOG.md
  scripts/comments_to_running_notes.py
Labels: bug, no validation

#268 Fix bug that control has no project id in index checker
  VERSIONLOG.md
  scripts/index_distance_checker.py
Labels: bug, no validation

#269 Use the longer read for demux threshold
  VERSIONLOG.md
  scripts/manage_demux_stats.py
Labels: enhancement, no validation

#270 Update Qubit EPP scripts to handle FLEX file format
  VERSIONLOG.md
  scripts/copy_qubit.py
Labels: enhancement, validation
