Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2023-07, with the labels that each got.

#259 Calculate fmol AND ng amounts in QC, if possible
  VERSIONLOG.md
  scripts/qc_amount_calculation.py
Labels: enhancement, no validation

#260 Polish ONT EPPs
  VERSIONLOG.md
  scripts/ont_generate_samplesheet.py
Labels: bug, enhancement, no validation

#261 Bugfix
  VERSIONLOG.md
  scripts/ont_send_loading_info_to_db.py
Labels: bug, enhancement, no validation

#262 Fix bug in generating Anglerfish samplesheet for samples w/o ONT barcodes
  VERSIONLOG.md
  scripts/ont_generate_samplesheet.py
Labels: bug, no validation

#263 Add function to verify sample name format in index_distance_checker
  VERSIONLOG.md
  scripts/index_distance_checker.py
Labels: enhancement, no validation

#264 Add NovaSeqXPlus in sequencing step list for readscount
  VERSIONLOG.md
  scripts/readscount.py
Labels: enhancement, no validation

#265 Update index distance checker to verify sample names
  VERSIONLOG.md
  scripts/index_distance_checker.py
Labels: enhancement, no validation
