Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2023-11, with the labels that each got.

#284 Remove obsoleted EPP scripts; Refactor UDF names for library prep amount
  VERSIONLOG.md
  data/logbook_data.py
  scripts/amount_check.py
  scripts/bravo_csv.py
  scripts/genotyping_value_carrying.py
  scripts/read_neoprep_log.py
  scripts/update_amount_left.py
  scripts/volume_calculation.py
  scripts/write_neoprep_csv.py
  scripts/zika_methods.py
  scripts/zika_utils.py
Labels: enhancement, validation

#271 Update BioAnalyzer step
  VERSIONLOG.md
  scilifelab_epps/epp.py
  scripts/parse_ba_results.py
Labels: enhancement, validation, WIP

#286 Improve logging for Zika normalization and docs
  VERSIONLOG.md
  scripts/zika_methods.py
  scripts/zika_utils.py
Labels: enhancement, no validation

#287 Hotfix, fix import syntax
  scripts/zika_methods.py
Labels: bug, no validation

#288 Fix error for RAD-seq pooling
  VERSIONLOG.md
  scripts/bravo_csv.py
Labels: bug, no validation

#290 Fix change in flowcell mode name that is related with control software upgrade
  VERSIONLOG.md
  scripts/illumina_run_parameter_parser.py
Labels: bug, no validation

#289 Re-write EPP for parsing Anglerfish results
  VERSIONLOG.md
  scripts/parse_anglerfish_results.py
Labels: enhancement, no validation
