Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2024-11, with the labels that each got.

#380 Bugfix BioAnalyzer results pasing
  VERSIONLOG.md
  scripts/parse_ba_results.py
Labels: bug, no validation

#374 AVITI manifest improvements
  VERSIONLOG.md
  scripts/generate_aviti_run_manifest.py
Labels: enhancement, no validation

#379 Additional lane thresholds for AVITI
  VERSIONLOG.md
  scripts/manage_demux_stats.py
  scripts/manage_demux_stats_thresholds.py
Labels: enhancement, no validation

#381 Add col for qPCR dilution vol
  VERSIONLOG.md
  scripts/bravo_csv.py
Labels: enhancement, validation
