Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2024-01, with the labels that each got.

#296 Supplement BA EPP with additional name check
  scripts/parse_ba_results.py
Labels: enhancement, no validation

#299 Fix issues appearing after deploment of PR #293
  .editorconfig
  .git-blame-ignore-revs
  .github/pr_labels.yml
  .github/workflows/lint-code.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  data/QC_criteria.json
  data/SMARTSEQ3_indexes.json
  requirements-dev.txt
  requirements.txt
Labels: bug, enhancement, validation

#300 Parse Anglerfish dataframe instead of textfile and improve code factoring
  scripts/parse_anglerfish_results.py
Labels: enhancement, no validation

#301 Fix exits and pre-commit config
  .pre-commit-config.yaml
  scripts/novaseq_run_recipe_generator.py
  scripts/ont_calc_volumes.py
  scripts/ont_generate_samplesheet.py
  scripts/ont_pool.py
  scripts/ont_suggest_ports.py
  scripts/ont_update_amount.py
  scripts/parse_ba_results.py
  scripts/samplesheet_generator.py
  scripts/tecan_parser.py
  scripts/write_notes_to_couchdb.py
Labels: enhancement, no validation

#302 Add GitHub action to check versionlog has been updated for a PR
  .github/workflows/check-log.yml
  .github/workflows/lint-code.yml
  .gitignore
  VERSIONLOG.md
Labels: enhancement, no validation

#303 Enable copy_field_art2samp to copy values from Aggregate QC steps
  VERSIONLOG.md
  scripts/copy_field_art2samp.py
  scripts/write_notes_to_couchdb.py
Labels: enhancement, no validation

#304 Broaden anglerfish run search
  VERSIONLOG.md
  scripts/parse_anglerfish_results.py
Labels: enhancement, no validation

#305 Update Anglerfish parsing to handle runs w/o ONT barcodes
  VERSIONLOG.md
  scripts/parse_anglerfish_results.py
Labels: bug, enhancement, no validation
