Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2024-06, with the labels that each got.

#336 Support VC100 in logbook
  VERSIONLOG.md
  data/logbook_data.py
Labels: enhancement, validation

#338 Skip warning message for distance of special indexes
  VERSIONLOG.md
  scripts/samplesheet_generator.py
Labels: enhancement, no validation

#337 Fix sample-to-index linkage in ONT library parsing
  VERSIONLOG.md
  scripts/generate_anglerfish_samplesheet.py
  scripts/generate_minknow_samplesheet.py
Labels: bug, enhancement, no validation
