Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2024-09, with the labels that each got.

#348 Fix bug
  VERSIONLOG.md
  scripts/manage_demux_stats.py
Labels: bug, no validation

#349 Fix bug with zika module import
  VERSIONLOG.md
  scilifelab_epps/zika/__init__.py
Labels: bug, no validation

#350 ruff format
  VERSIONLOG.md
  scilifelab_epps/zika/__init__.py
Labels: bug, no validation

#351 Include Project name and sequencing setup in AVITI run manifest
  VERSIONLOG.md
  scripts/generate_aviti_run_manifest.py
Labels: enhancement, no validation

#353 Fix bug with zika module import cont; Change project format for AVITI…
  VERSIONLOG.md
  scilifelab_epps/utils/__init__.py
  scilifelab_epps/zika/__init__.py
  scripts/generate_aviti_run_manifest.py
Labels: enhancement, no validation

#354 In short, resort to a new sort of port sort
  VERSIONLOG.md
  scripts/ont_suggest_ports.py
Labels: enhancement, no validation

#356 Support both single lane and dual lane of AVITI flowcell
  VERSIONLOG.md
  scripts/generate_aviti_run_manifest.py
Labels: enhancement, no validation

#355 Implement ONT logbooks
  VERSIONLOG.md
  data/logbook_data.py
  scripts/logbook_service_account.py
Labels: enhancement, no validation

#357 Bugfix for MinKNOW ss generation of ONT labeled single samples
  VERSIONLOG.md
  scripts/generate_minknow_samplesheet.py
Labels: enhancement, no validation

#360 Update AVITI run stats parser to handle multiple lanes
  VERSIONLOG.md
  scripts/aviti_run_parameter_parser.py
Labels: enhancement, no validation

#361 Support AVITI protocols for lobgook and comments_to_RN
  VERSIONLOG.md
  data/logbook_data.py
  scripts/comments_to_running_notes.py
Labels: enhancement, no validation

#362 Fix bugs with EPP in the BCL conversion step
  VERSIONLOG.md
  scripts/manage_demux_stats.py
  scripts/manage_demux_stats_thresholds.py
Labels: bug, no validation

#363 New EPP for parsing VC100 CSV file
  VERSIONLOG.md
  scripts/parse_vc100_results.py
Labels: enhancement, validation

#364 Fix bug with data type in frag_an_driver_gen
  VERSIONLOG.md
  scripts/frag_an_driver_gen.py
Labels: bug, no validation

#366 Add 10X steps to comments-to-running-notes config
  VERSIONLOG.md
  scripts/comments_to_running_notes.py
Labels: enhancement, no validation
