Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2025-04, with the labels that each got.

#409 Convert list of artifacts to set to get unique values
  VERSIONLOG.md
  scripts/runningnotes_from_sequencing.py
Labels: bug, no validation

#407 Introduce work-around for LIMS bug of demux artifacts having multiple sample associations
  VERSIONLOG.md
  scilifelab_epps/epp.py
  scripts/fix_demux_artifact_names.py
  scripts/generate_aviti_run_manifest.py
  scripts/generate_minknow_samplesheet.py
  scripts/manage_demux_stats.py
Labels: bug, no validation

#413 Demux patch
  VERSIONLOG.md
  scripts/manage_demux_stats.py
Labels: no validation

#403 Introduce EPP for generic UDF calculations
  VERSIONLOG.md
  scilifelab_epps/utils/udf_tools.py
  scripts/calculate_udf_formulas.py
Labels: enhancement, no validation

#412 Improve SQL for pool sample-label mapping
  VERSIONLOG.md
  scilifelab_epps/epp.py
Labels: no validation
