Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2025-01, with the labels that each got.

#385 Replace PR label checker
  .github/pr_labels.yml
  .github/workflows/check_pr_label.yml
  VERSIONLOG.md
Labels: no validation

#387 Ruff 0.9.2 format
  VERSIONLOG.md
  scilifelab_epps/calc_from_args/calculation_methods.py
  scilifelab_epps/epp.py
  scilifelab_epps/utils/udf_tools.py
  scilifelab_epps/zika/methods.py
  scripts/calculate_cell_nuclei_conc.py
  scripts/copy_field_art2samp.py
  scripts/copy_field_proc2projs.py
  scripts/copy_frag_an.py
  scripts/copy_qubit.py
  scripts/copy_reference_genome.py
  scripts/generate_anglerfish_samplesheet.py
  scripts/generate_aviti_run_manifest.py
  scripts/generate_minknow_samplesheet.py
  scripts/index_distance_checker.py
  scripts/logbook.py
  scripts/logbook_service_account.py
  scripts/molar_concentration.py
  scripts/multiply_with_dilution_fold.py
  scripts/ont_calc_volumes.py
  scripts/ont_pool.py
  scripts/ont_send_reloading_info_to_db.py
  scripts/ont_suggest_ports.py
  scripts/ont_sync_to_db.py
  scripts/parse_anglerfish_results.py
  scripts/parse_caliper_results.py
  scripts/parse_vc100_results.py
  scripts/qc_amount_calculation.py
  scripts/quality_filter.py
  scripts/quantit_generate_driver_file.py
  scripts/quantit_set_QC.py
  scripts/quantit_set_conc.py
  scripts/set_App_QC.py
  scripts/undemultiplexed_index.py
  scripts/zebra_barcodes.py
Labels: enhancement, no validation

#384 EPP to recusively fetch last recorded derived sample UDF
  VERSIONLOG.md
  scilifelab_epps/calc_from_args/udf_arg_methods.py
  scilifelab_epps/utils/udf_tools.py
  scilifelab_epps/zika/utils.py
  scripts/fetch_last_known_field.py
  scripts/log_udfs.py
  scripts/ont_calc_volumes.py
  scripts/ont_update_amount.py
Labels: enhancement, validation

#392 Trim parenthesized content from sample names in MinKNOW samplesheet
  VERSIONLOG.md
  scripts/generate_minknow_samplesheet.py
Labels: enhancement, no validation
