Repository NationalGenomicsInfrastructure/scilifelab_epps, pull requests merged in 2025-03, with the labels that each got.

#397 Update formulas to match updated NEB calc tool, assuming deprotonated phosphate hydroxyls
  VERSIONLOG.md
  scilifelab_epps/utils/formula.py
Labels: enhancement, no validation

#398 Apply uppercase to flowcell ID (with updated VERSIONLOG.md)
  VERSIONLOG.md
  scripts/samplesheet_generator.py
Labels: no validation

#400 Hotfix (critical) from #399
  VERSIONLOG.md
  scilifelab_epps/epp.py
Labels: no validation

#401 Handle missing PercentMismatch for samples in IndexAssignment.csv
  VERSIONLOG.md
  scripts/manage_demux_stats.py
Labels: no validation

#404 ONT barcoding changes
  VERSIONLOG.md
  data/ONT_barcodes.py
  scripts/generate_anglerfish_samplesheet.py
  scripts/generate_minknow_samplesheet.py
Labels: bug, no validation
